version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: anka_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anka
      MYSQL_USER: anka_user
      MYSQL_PASSWORD: anka_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: anka_backend
    restart: always
    environment:
      DATABASE_URL: mysql://root:root@localhost:3306/anka
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
    build: ./frontend
    container_name: anka_frontend
    restart: always
    ports:
      - "3002:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    working_dir: /app

volumes:
  mysql_data:
