version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: anka_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anka
      MYSQL_USER: anka_user
      MYSQL_PASSWORD: anka_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
